/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SqlRouteImport } from "./routes/sql"
import { Route as SchedulerRouteImport } from "./routes/scheduler"
import { Route as LogsRouteImport } from "./routes/logs"
import { Route as FunctionsRouteImport } from "./routes/functions"
import { Route as DataRouteImport } from "./routes/data"
import { Route as IndexRouteImport } from "./routes/index"

const SqlRoute = SqlRouteImport.update({
  id: "/sql",
  path: "/sql",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/sql.lazy").then((d) => d.Route))
const SchedulerRoute = SchedulerRouteImport.update({
  id: "/scheduler",
  path: "/scheduler",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/scheduler.lazy").then((d) => d.Route))
const LogsRoute = LogsRouteImport.update({
  id: "/logs",
  path: "/logs",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/logs.lazy").then((d) => d.Route))
const FunctionsRoute = FunctionsRouteImport.update({
  id: "/functions",
  path: "/functions",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/functions.lazy").then((d) => d.Route))
const DataRoute = DataRouteImport.update({
  id: "/data",
  path: "/data",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/data.lazy").then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/data": typeof DataRoute
  "/functions": typeof FunctionsRoute
  "/logs": typeof LogsRoute
  "/scheduler": typeof SchedulerRoute
  "/sql": typeof SqlRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/data": typeof DataRoute
  "/functions": typeof FunctionsRoute
  "/logs": typeof LogsRoute
  "/scheduler": typeof SchedulerRoute
  "/sql": typeof SqlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/data": typeof DataRoute
  "/functions": typeof FunctionsRoute
  "/logs": typeof LogsRoute
  "/scheduler": typeof SchedulerRoute
  "/sql": typeof SqlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/data" | "/functions" | "/logs" | "/scheduler" | "/sql"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/data" | "/functions" | "/logs" | "/scheduler" | "/sql"
  id:
    | "__root__"
    | "/"
    | "/data"
    | "/functions"
    | "/logs"
    | "/scheduler"
    | "/sql"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  FunctionsRoute: typeof FunctionsRoute
  LogsRoute: typeof LogsRoute
  SchedulerRoute: typeof SchedulerRoute
  SqlRoute: typeof SqlRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sql": {
      id: "/sql"
      path: "/sql"
      fullPath: "/sql"
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/scheduler": {
      id: "/scheduler"
      path: "/scheduler"
      fullPath: "/scheduler"
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/logs": {
      id: "/logs"
      path: "/logs"
      fullPath: "/logs"
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/functions": {
      id: "/functions"
      path: "/functions"
      fullPath: "/functions"
      preLoaderRoute: typeof FunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/data": {
      id: "/data"
      path: "/data"
      fullPath: "/data"
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  FunctionsRoute: FunctionsRoute,
  LogsRoute: LogsRoute,
  SchedulerRoute: SchedulerRoute,
  SqlRoute: SqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
